* 4clojure for Android

  This is the source code for unofficial 4cljojure Android application. The app
  is a client for [[http://4clojure.com][4clojure.com]], which is a website for solving Clojure koans
  (short programming problems). 4clojure for Android allows solving these koans
  on your mobile phone, without entering the browser, in both online and offline
  mode.

  Features so far:

  - Full synchronization with server (new problems and solutions are
    downloaded automatically)
  - Full offline support (network is not required to solve problems,
    solutions can be synchronized later)
  - In-client registration

  Plans for future:
  - Proper code editor (with highlighting and indentation)
  - Integration with Clojail

* How to build

  Execute =lein droid doall= inside the repository.

* Acknowledgments

  I thank 4clojure.com team for developing and maintaining this great resource,
  and for allowing me to base this application upon their work.

* License

  Copyright © 2015 Alexander Yakushev. Distributed under the Eclipse Public
  License, the same as Clojure. See the file [[https://github.com/alexander-yakushev/foreclojure-android/blob/master/LICENSE][LICENSE]].

  4clojure.com data and logo is available under the EPL v 1.0 license.

  Green check icon is taken from [[http://iconbug.com/detail/icon/859/green-check/][iconbug.com]] and is provided under CC BY-ND 3.0.
